AppToken:123456
ClickLogin:
ClickPayment:
PaymentIapClicked:
PaymentWalletClicked:
ClickRegister:
ClickSync:
LoginFailed:
ClickLoginFB:
LoginFBFailed:
LoginFBSucess:
ClickLoginGG:
LoginGGFailed:
LoginGGSucess:
LoginSuccess:
PaymentFailed:
PaymentIapCancel:
PaymentIapRevenue:
PaymentIapSuccess:
PaymentSuccess:
PaymentTotalRevenue:
PaymentWalletCancel:
PaymentWalletRevenue:
PaymentWalletSuccess:
ClickQP:
LoginQPFailed:
LoginQPSuccess:
RegisterFailed:
RegisterSuccess:
SyncAccountFailed:
SyncAccountSuccess:
TotalPayment: